### ISSUE TITLE
全体管理

### ISSUE THREAD

**Issue by yusukegunji** [camp-team/team-gunji#15]
## MTG
- [x] 企画MTG (2020.11.23 20:00~)
- [x] 設計MTG (2020.11.28 16:00~)
- [x] 担当振MTG (2020.12.3 20:00~)
- [x] キックオフMTG (2020.12.5 10:00~)

### 事前準備

- [x] 要件定義、DB設計
- [x] Issue立て
- [x] ワイヤーフレーム作成
- [x] アバター選定
- [x] ルームデザイン
- [x] プロダクト名

 ### 環境構築 #2 

- [x] Angular v11.0.2
- [x] Firebase v8.16.2
- [x] AngularMaterial v11.0.1
- [x] Prettier
- [x] GitHubActions

 ### 画面

- [x] ヘッダー #3 
- [x] フッター #4 
- [x] ウェルカム画面 (ログイン画面) → 新規登録(アバター選択遷移)&ログイン(ホーム画面遷移) #5 
- [x] アバター選択画面 (Swiper?) #6 
- [x] 間取り選択画面 (部屋作成画面) #7 
- [x] ホーム画面 (ルーム画面) #8 
- [x] 各部屋画面 (リビング/ダイニング/キッチン/バス/トイレ/玄関/寝室/デスク/ダイニング/ランドリー/ベランダ/全体...) #9 
- [x] ユーザー設定画面 (MatTab?) #10 

 ### 機能

- [x] ログイン (Google/メールパスワード) / ログアウト #11 
- [x] ユーザー作成 #12 
- [x] ルーム作成 #13 
- [x] タスク完了 #14 
- [x] ウンチ出現 #16 
- [x] アラートメール送信 (SendGrid) #15 

 ### 余裕があれば

 #### 画面
 
- [ ] アイテムゲットダイアログ
- [ ] みんなのルーム一覧画面
- [ ] ユーザー画面/獲得アイテム一覧
- [ ] ショップ画面

 #### 機能

- [ ] アイテムゲット
- [ ] ルームにいいね
- [ ] ルームに訪問

 ## 設計

### 画面
![image](https://user-images.githubusercontent.com/60227737/100999951-9f626f80-35a0-11eb-9fad-36b2a12c1cc5.png)

### 機能
![image](https://user-images.githubusercontent.com/60227737/100999842-878aeb80-35a0-11eb-8163-9c19ab940110.png)

### DB
![image](https://user-images.githubusercontent.com/60227737/101000023-af7a4f00-35a0-11eb-9ff6-6cc641397c94.png)

 ## ワイヤーフレーム
https://xd.adobe.com/view/8b30a31f-f0a6-4fb1-8f18-5b802991e412-de63/
